# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?chembl_compound_id ?pubchem_id
WHERE {
  ?Molecule a cco:SmallMolecule ;
            cco:moleculeXref ?xref .
  ?xref a cco:PubchemRef .

  BIND (STRAFTER(STR(?Molecule), "http://rdf.ebi.ac.uk/resource/chembl/molecule/") AS ?chembl_compound_id)
  BIND (STRAFTER(STR(?xref), "http://pubchem.ncbi.nlm.nih.gov/compound/") AS ?pubchem_id)
}
# Paginate: 1000000