# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?chembl_compound_id ?chebi_id
WHERE {
  ?Molecule a cco:SmallMolecule ;
            cco:moleculeXref ?xref .
  ?xref a cco:ChebiRef .

  BIND (STRAFTER(STR(?Molecule), "http://rdf.ebi.ac.uk/resource/chembl/molecule/") AS ?chembl_compound_id)
  BIND (REPLACE(STRAFTER(STR(?xref), "http://www.ebi.ac.uk/chebi/searchId.do?chebiId="), "%3A", ":") AS ?chebi_id)
}
